runtime: nodejs10
instance_class: B1

basic_scaling:
  max_instances: 1

resources:
  cpu: .5
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  MONGO_CONNECTION: mongodb+srv://cinema_user:iel3cdb6rWzX7seV@cluster0-d96py.gcp.mongodb.net/test?retryWrites=true&w=majority
